name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          context: .
          submodules: true
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          context: .
          python-version: 3.9
      - name: Install sphinx
        run: |
          pip install -r requirements.txt
          cd countoscope/
          pip install -r requirements.txt
          pip install .
      - name: Build
        run: |
          cd docs/
          make clean
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
